#!/usr/bin/env bash

generate_ctags_in() {
  echo "Running ctags on $1"
  (cd "$1"; ctags -R --languages=ruby)
}

generate_ctags_for() {
  if [ -w "$1/lib/ruby" ]; then
    for dir in \
      "$1"/lib/ruby/[0-9]* \
      "$1"/lib/ruby/shared*
    do
      if [ -w $dir ]; then
        generate_ctags_in "$dir"
      fi
    done
    for dir in \
      "$1"/lib/ruby/site_ruby/[0-9]* \
      "$1"/lib/ruby/vendor_ruby/[0-9]*
    do
      if [ -w $dir ]; then
        [ "$(find "$dir" -name '*.rb'|wc -l)" = 0 ] || generate_ctags_in "$dir"
      fi
    done
  elif [ -w "$1/lib" ]; then
    generate_ctags_in "$1/lib"
  else
    echo "No directories for ctags found in $1" >&2
    return 1
  fi
}

generate_ctags_for $1
